Models/ToDo.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models;

public class ToDo {
    public int Id { get; set;}
    [Required(ErrorMessage = "Se requiere una descripción")]
    [StringLength(100, MinimumLength = 3,
    ErrorMessage = "{0} debe tener como minimo 1 caracter")]
    public string? Descripcion { get; set;}
    public bool Status { get; set;}
    public DateTime ReleaseDate { get; set; }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDoList.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToDoList.Models;
using ToDoList.Services;

namespace ToDoList.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    public List<ToDo> ToDos;
    [BindProperty]
    public ToDo newToDo { get; set; } = new();

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        ToDos = ToDoService.GetAll();
    }

    public IActionResult OnPostAdd(){
        if(!ModelState.IsValid){
            return Page();
        }
        ToDoService.Add(newToDo);
        return RedirectToAction("Get");
    }

    public IActionResult OnPostSwitchStatus(int id){
        ToDoService.SwitchStatus(id);
        return RedirectToAction("Get");
    }

    public IActionResult OnPostDelete(int id){
        ToDoService.Remove(id);
        return RedirectToAction("Get");
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDoList.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Index.cshtml
@page
@using ToDoList.Models
@model ToDoList.Pages.IndexModel
@{
    ViewData["Title"] = "Home page";
}
<form method="post" asp-page-handler="Add" class="mb-3 row">
    <label asp-for="newToDo.Descripcion" class="col-sm-2 col-form-label">Descripci&oacute;n</label>
    <div class="col-sm-8">
        <input asp-for="newToDo.Descripcion" class="form-control" placeholder="A&ntilde;ade una tarea"/>
        <span asp-validation-for="newToDo.Descripcion" class="form-text text-danger"></span>        
    </div>
    <button type="submit" class="btn btn-primary col-sm-2">+</button>
</form>

<h2> Pendientes </h2>

<ul>
@foreach (var todo in Model.ToDos){
    @if(!todo.Status){
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
                <form method="post" asp-page-handler="SwitchStatus" asp-route-id="@todo.Id">
                    <input type="checkbox" class="form-check-input me-3" onclick="form.submit();"/>
                </form>
                @todo.Descripcion
            </div>
            <form method="post" asp-page-handler="Delete" asp-route-id="@todo.Id">
                <button type="submit" class="btn btn-danger">-</button>
            </form>

        </li>
    }
}
</ul>

<h2> Completadas </h2>

<ul>
@foreach (var todo in Model.ToDos){
    @if(todo.Status){
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
                <form method="post" asp-page-handler="SwitchStatus" asp-route-id="@todo.Id">
                    <input type="checkbox" class="form-check-input me-3" checked onclick="form.submit();"/>
                </form>
                <div class="me-3">
                    @todo.Descripcion
                </div>
            </div>
            <form method="post" asp-page-handler="Delete" asp-route-id="@todo.Id">
                <button type="submit" class="btn btn-danger">-</button>
            </form>

        </li>
    }
}
</ul>


@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoList - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>